### ISSUE TITLE
Chapter 1 :: Example Needed

### ISSUE THREAD

**Issue by GabsPalomo** [atyre2/NRES450_book#4]
I believe that it's a good idea to include an example in Chapter 1 after you start talking about "Where things get interesting...". You mention that things get interesting when N depends on the abundance of other species. That this is one of the things that make population dynamics very interesting (I agree!). So an example that shows exactly this, without looking at the model. Just showing how the N of one species affects the N of another species is an easy concept that can make this "abstract" idea more concrete. The abundance of seals affects the abundance of sea otters. The students are not supposed to read anything more than just that.

**Comment by atyre2** [comment]
Yes, example is a great idea. The problem is the two species part ... not sure that's good this early in the book. But I don't feel strongly enough to not accept it!
